# conformal.py
"""
Conformal (Möbius) infinitesimal generators in R^d.

For d >= 3, the (global) conformal group of Euclidean space is finite-dimensional and
generated by:
- Translations:          T_i(x) = e_i
- Rotations:             R_{ij}(x) = x_i ∂_j - x_j ∂_i
- Dilation:              D(x) = x
- Special conformals:    K_i(x) = 2 x_i x - ||x||^2 e_i

For d = 2, these 6 generators correspond to the global conformal group (Möbius)
when compactified to the Riemann sphere via stereographic projection.

Backend behavior matches the Euclidean Killing implementation:
- backend='auto'  : dispatch based on input type (np vs torch) per call
- backend='numpy' : always numpy
- backend='torch' : always torch

Ordering (when all included):
  [T_0..T_{d-1}, R_0_1..R_{d-2}_{d-1}, D, K_0..K_{d-1}]
"""

from __future__ import annotations
from typing import Callable, List, Tuple, Literal

import numpy as np

__all__ = [
    "generate_conformal_fields",
    "generate_conformal_fields_with_names",
]

Backend = Literal["auto", "numpy", "torch"]


# ----------------------------- lazy torch helpers -----------------------------

def _maybe_import_torch():
    try:
        import torch  # type: ignore
        return torch
    except Exception:
        return None

def _is_torch_tensor(x) -> bool:
    return x.__class__.__module__.startswith("torch") and hasattr(x, "dtype") and hasattr(x, "device")

def _to_numpy(x) -> np.ndarray:
    if isinstance(x, np.ndarray):
        return x
    if _is_torch_tensor(x):
        return x.detach().cpu().numpy()
    return np.asarray(x)

def _to_torch(x, dtype=None, device=None):
    torch = _maybe_import_torch()
    if torch is None:
        raise RuntimeError("backend='torch' requested but PyTorch is not available.")
    if isinstance(x, torch.Tensor):
        if dtype is not None or device is not None:
            return x.to(dtype=dtype or x.dtype, device=device or x.device)
        return x
    t = torch.as_tensor(x)
    if dtype is not None or device is not None:
        t = t.to(dtype=dtype or t.dtype, device=device or t.device)
    return t


# ------------------------------- batch helpers -------------------------------

def _ensure_batch_numpy(x: np.ndarray) -> Tuple[np.ndarray, bool]:
    x = _to_numpy(x).astype(np.float64, copy=False)
    if x.ndim == 1:
        return x.reshape(1, -1), True
    if x.ndim == 2:
        return x, False
    raise ValueError("Input must be shape (d,) or (N, d).")

def _ensure_batch_torch(x):
    torch = _maybe_import_torch()
    assert torch is not None
    xt = _to_torch(x)
    if xt.ndim == 1:
        return xt.unsqueeze(0), True
    if xt.ndim == 2:
        return xt, False
    raise ValueError("Input must be shape (d,) or (N, d).")


# --------------------------- numpy field constructors -------------------------

def _make_translation_numpy(d: int, i: int) -> Callable[[np.ndarray], np.ndarray]:
    e = np.zeros((d,), dtype=np.float64)
    e[i] = 1.0
    def T(x: np.ndarray) -> np.ndarray:
        X, was_single = _ensure_batch_numpy(x)
        out = np.tile(e, (X.shape[0], 1))
        return out[0] if was_single else out
    return T

def _make_rotation_numpy(d: int, i: int, j: int) -> Callable[[np.ndarray], np.ndarray]:
    def R(x: np.ndarray) -> np.ndarray:
        X, was_single = _ensure_batch_numpy(x)
        out = np.zeros_like(X)
        out[:, i] = -X[:, j]
        out[:, j] =  X[:, i]
        return out[0] if was_single else out
    return R

def _make_dilation_numpy(d: int) -> Callable[[np.ndarray], np.ndarray]:
    def D(x: np.ndarray) -> np.ndarray:
        X, was_single = _ensure_batch_numpy(x)
        out = X.copy()
        return out[0] if was_single else out
    return D

def _make_special_conformal_numpy(d: int, i: int) -> Callable[[np.ndarray], np.ndarray]:
    def K(x: np.ndarray) -> np.ndarray:
        X, was_single = _ensure_batch_numpy(x)
        r2 = np.sum(X * X, axis=1, keepdims=True)          # (N,1)
        xi = X[:, [i]]                                     # (N,1)
        out = 2.0 * xi * X                                 # (N,d)
        out[:, i] -= r2[:, 0]                              # subtract ||x||^2 e_i
        return out[0] if was_single else out
    return K


# --------------------------- torch field constructors -------------------------

def _make_translation_torch(d: int, i: int) -> Callable:
    torch = _maybe_import_torch()
    assert torch is not None
    def T(x):
        Xt, was_single = _ensure_batch_torch(x)
        out = torch.zeros_like(Xt)
        out[:, i] = 1.0
        return out[0] if was_single else out
    return T

def _make_rotation_torch(d: int, i: int, j: int) -> Callable:
    torch = _maybe_import_torch()
    assert torch is not None
    def R(x):
        Xt, was_single = _ensure_batch_torch(x)
        out = torch.zeros_like(Xt)
        out[:, i] = -Xt[:, j]
        out[:, j] =  Xt[:, i]
        return out[0] if was_single else out
    return R

def _make_dilation_torch(d: int) -> Callable:
    torch = _maybe_import_torch()
    assert torch is not None
    def D(x):
        Xt, was_single = _ensure_batch_torch(x)
        out = Xt.clone()
        return out[0] if was_single else out
    return D

def _make_special_conformal_torch(d: int, i: int) -> Callable:
    torch = _maybe_import_torch()
    assert torch is not None
    def K(x):
        Xt, was_single = _ensure_batch_torch(x)
        r2 = torch.sum(Xt * Xt, dim=1, keepdim=True)       # (N,1)
        xi = Xt[:, [i]]                                     # (N,1)
        out = 2.0 * xi * Xt                                 # (N,d)
        out[:, i] = out[:, i] - r2[:, 0]
        return out[0] if was_single else out
    return K


# ------------------------------- backend wrapper ------------------------------

def _wrap_backend(field_np: Callable, field_torch: Callable, backend: Backend) -> Callable:
    if backend == "numpy":
        def f(x):
            return field_np(_to_numpy(x))
        return f

    if backend == "torch":
        torch = _maybe_import_torch()
        if torch is None:
            raise RuntimeError("backend='torch' requested but PyTorch is not available.")
        def f(x):
            x_t = _to_torch(x)
            return field_torch(x_t)
        return f

    # backend == "auto"
    def f(x):
        if _is_torch_tensor(x):
            return field_torch(x)
        return field_np(x)
    return f


# --------------------------------- public API --------------------------------

def generate_conformal_fields(
    d: int,
    include_translations: bool = True,
    include_rotations: bool = True,
    include_dilation: bool = True,
    include_special_conformal: bool = True,
    backend: Backend = "auto",
) -> List[Callable]:
    if d <= 0:
        raise ValueError("Dimension d must be positive.")

    fields: List[Callable] = []

    if include_translations:
        for i in range(d):
            fields.append(_wrap_backend(
                _make_translation_numpy(d, i),
                _make_translation_torch(d, i),
                backend
            ))

    if include_rotations:
        for i in range(d):
            for j in range(i + 1, d):
                fields.append(_wrap_backend(
                    _make_rotation_numpy(d, i, j),
                    _make_rotation_torch(d, i, j),
                    backend
                ))

    if include_dilation:
        fields.append(_wrap_backend(
            _make_dilation_numpy(d),
            _make_dilation_torch(d),
            backend
        ))

    if include_special_conformal:
        for i in range(d):
            fields.append(_wrap_backend(
                _make_special_conformal_numpy(d, i),
                _make_special_conformal_torch(d, i),
                backend
            ))

    if not fields:
        raise ValueError("At least one generator family must be included.")
    return fields


def generate_conformal_fields_with_names(
    d: int,
    include_translations: bool = True,
    include_rotations: bool = True,
    include_dilation: bool = True,
    include_special_conformal: bool = True,
    backend: Backend = "auto",
) -> Tuple[List[Callable], List[str]]:
    fields: List[Callable] = []
    names: List[str] = []

    if include_translations:
        for i in range(d):
            fields.append(_wrap_backend(
                _make_translation_numpy(d, i),
                _make_translation_torch(d, i),
                backend
            ))
            names.append(f"T_{i}")

    if include_rotations:
        for i in range(d):
            for j in range(i + 1, d):
                fields.append(_wrap_backend(
                    _make_rotation_numpy(d, i, j),
                    _make_rotation_torch(d, i, j),
                    backend
                ))
                names.append(f"R_{i}_{j}")

    if include_dilation:
        fields.append(_wrap_backend(
            _make_dilation_numpy(d),
            _make_dilation_torch(d),
            backend
        ))
        names.append("D")

    if include_special_conformal:
        for i in range(d):
            fields.append(_wrap_backend(
                _make_special_conformal_numpy(d, i),
                _make_special_conformal_torch(d, i),
                backend
            ))
            names.append(f"K_{i}")

    if not fields:
        raise ValueError("At least one generator family must be included.")
    return fields, names
